import type { UsersProperties } from '../../interfaces';

export const disable2FADescription: UsersProperties = [
	{
		displayName: 'OTP',
		name: 'otp',
		type: 'string',
		displayOptions: {
			show: {
				operation: ['disable2FA'],
				resource: ['users'],
			},
		},
		placeholder: '859014',
		default: '',
		description: 'One-time password generated by the authenticator app',
		required: true,
	},
];
